import {Platform, StyleSheet} from 'react-native';
import {COLORS} from '@colors';
import {getSize} from '@util/responsive';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  status_container: {
    width: '85%',
    height: '85%',
    borderRadius: 20,
    borderWidth: 1,
    backgroundColor: COLORS.white,
    borderColor: '#f5f5f5',
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOpacity: 0.8,
    elevation: 6,
    shadowRadius: 15,
    shadowOffset: {width: 1, height: 13},
  },
  icons_container: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: COLORS.offwhite,
    top: -25,
  },
  header_container: {
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: getSize.m(20),
  },
  header: {
    fontStyle: 'normal',
    fontWeight: 'bold',
    color: COLORS.primary,
    fontSize: 16,
  },
  sub_header: {
    fontStyle: 'normal',
    fontWeight: 'bold',
    color: COLORS.primary,
    fontSize: 12,
  },

  info_container: {
    backgroundColor: '#fff',
    paddingHorizontal: getSize.m(10),
    paddingVertical: getSize.m(10),
    borderColor: COLORS.white,
    borderWidth: 1,
    borderTopColor: COLORS.primary,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOpacity: 0.8,
    elevation: 6,
    shadowRadius: 15,
    shadowOffset: {width: 1, height: 13},
  },
  driver_info: {
    backgroundColor: '#fff',
    paddingHorizontal: getSize.m(10),
    paddingVertical: 10,
    borderColor: COLORS.white,
    borderWidth: 1,
    borderTopColor: COLORS.primary,
    borderRadius: 20,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOpacity: 0.8,
    elevation: 6,
    shadowRadius: 15,
    shadowOffset: {width: 1, height: 13},
  },
  location: {
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    justifyContent: 'space-between',
    elevation: 10,
    marginBottom: 10,
  },
  recipient: {
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    elevation: 10,
    marginBottom: 10,
  },
  note: {
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    elevation: 10,
  },
  text_header: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 30,
  },
  text_sub_header: {
    color: COLORS.black,
    fontWeight: 'bold',
    fontSize: 18,
  },
  text_footer: {
    color: '#05375a',
    fontSize: 18,
  },
  text_info: {
    color: COLORS.primary,
    fontSize: 16,
    fontStyle: 'normal',
    marginStart: 10,
  },
  time_text: {
    flex: 1,
    marginTop: Platform.OS === 'ios' ? 0 : -12,
    paddingLeft: 10,
    color: COLORS.primary,
    paddingTop: 10,
    fontSize: 16,
    fontStyle: 'normal',
  },
  action: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#f2f2f2',
    marginTop: 10,
    marginBottom: 10,
  },
  notification: {
    marginTop: 10,
    paddingHorizontal: 20,
    alignContent: 'center',
    justifyContent: 'center',
  },
  notification_text: {
    color: COLORS.primary,
  },
  button_container: {
    width: '100%',
    height: '12%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    width: '50%',
    height: '50%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: COLORS.primary,
    shadowColor: 'rgba(0, 0, 0, 0.1)',
    shadowOpacity: 0.8,
    elevation: 6,
    shadowRadius: 15,
    shadowOffset: {width: 1, height: 13},
  },
  button_text: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.white,
  },
});
