import {Platform, StyleSheet} from 'react-native';
import {COLORS} from '@colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.primary,
  },
  header: {
    flexDirection: 'row',
    marginTop: 50,
    paddingHorizontal: 20,
    paddingBottom: 10,
  },
  footer: {
    flex: 1,
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  location: {
    borderStyle: 'solid',
    borderColor: COLORS.offwhite,
    borderWidth: 1.2,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  recipient: {
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    elevation: 10,
    marginBottom: 10,
  },
  note: {
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    elevation: 10,
  },
  text_header: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 30,
  },
  text_sub_header: {
    color: COLORS.black,
    fontWeight: 'bold',
    fontSize: 16,
  },
  text_footer: {
    color: '#05375a',
    fontSize: 18,
  },
  text_info: {
    color: COLORS.primary,
    fontSize: 16,
    fontStyle: 'normal',
    marginStart: 10,
  },
  time_text: {
    flex: 1,
    marginTop: Platform.OS === 'ios' ? 0 : -12,
    paddingLeft: 10,
    color: COLORS.primary,
    paddingTop: 10,
  },
  action: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#f2f2f2',
    width: '100%',
    marginTop: 16,
    marginBottom: 16,
  },
  logo: {
    resizeMode: 'cover',
    width: 20, // Adjust the width and height to your desired size
    height: 20,
    borderRadius: 10,
    borderColor: COLORS.primary,
    marginRight: 10,
  },
  time_action: {
    flexDirection: 'column',
    marginStart: 10,
  },
  actionError: {
    flexDirection: 'row',
    marginTop: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#FF0000',
    paddingBottom: 5,
  },
  textInput: {
    flex: 1,
    marginTop: Platform.OS === 'ios' ? 0 : -12,
    paddingLeft: 10,
    color: COLORS.primary,
    borderColor: COLORS.primary,
    fontWeight: 'bold',
  },
  errorMsg: {
    color: '#FF0000',
    fontSize: 14,
  },
  button: {
    alignItems: 'center',
    marginBottom: 10,
  },
  signIn: {
    width: '100%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    borderColor: COLORS.transparent,
    shadowColor: COLORS.black,
    shadowOffset: {width: 1, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  textSign: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.white,
  },
});
